GET https://telemedicine-pilot-d2anbuaxedbfdba9.eastus-01.azurewebsites.net/doctor/login
Content-Type: application/json

{
"email": "dr.khaled@example.com", 
"password": "hashed_password_11"  
}

###

PUT http://localhost:3000/doctor/edit/info
Content-Type: application/json

{
"firdtName": "",
"lastName": "",
"email": "",
"gender": "",
"phone": "",
"birthYear": 2001,
"residenceCountry": "",
"sixtyMinPrice": 0,
"thirtyMinPrice": 0,
"specialization": "",
"languages": ["Arabic", "English"]
}

###

GET http://localhost:3000/doctor/profile/info
Content-Type: application/json

{}